[project]
name = "oncp"
version = "0.0.0"
authors = [
	{ name="Johan Hallberg Szabadvary", email="johan.hallberg.szabadvary@ju.se" },
]
description = "An implementation of online conformal prediction"
readme = "README.md"
dependencies = [
	'numpy',
	'scipy',
]
classifiers = [
	"Development Status :: 2 - Pre-Alpha",
	"Programming Language :: Python :: 3",
	# TODO: choose a license
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage"    = "https://github.com/egonmedhatten/OnlineConformalPrediction"
"Bug Tracker" = "https://github.com/egonmedhatten/OnlineConformalPrediction/issues"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.setuptools.packages.find]
where = ["src"]
