#!/bin/bash
#
# This runs all Python files in src's root
# from the command line.
#
# This is intended to be run from CI.

set -e

export PYTHONPATH=src

for module in src/online_cp/*.py tests/*.py
do
	[ "$module" == src/online_cp/__init__.py ] && continue
	echo python $module
	/usr/bin/time -f "%es  (python $module)\n" \
	python $module
done
