#!/bin/bash
#
# This runs all notebooks in the notebooks folder
# from the command line and generate HTMLs.
#
# This is intended to be run from CI.

set -e

for notebook in notebooks/*.ipynb
do
	PYTHONPATH=../src jupyter-nbconvert --execute $notebook --to html
done
