#!/bin/bash
#
# Runs the test suite with coverage tracking
# and reports the results.
#
# This is intended to be run from CI.

set -e

export PYTHONPATH=src
coverage erase
coverage run -m pytest tests/ -q
coverage report
