name: docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.3"
      
      - name: Install dependencies
        run: |
          uv pip install hatchling mkdocs-material "mkdocstrings[python]" mkdocs-macros-plugin
          uv build
          uv pip install dist/*.whl
      
      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
