name: docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/uv-setuptools@v0.2
        with:
          python-version: "3.12"
      - run: uv pip install --extra docs mkdocs-material "mkdocstrings[python]" mkdocs-macros-plugin
      - run: uv run --extra docs mkdocs gh-deploy --force
