name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 # 2023-2024
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest nbconvert ipykernel scikit-learn scipy matplotlib validate-pyproject trove-classifiers coverage
      - name: Parse libraries and run doctests (./scripts/run-modules)
        run: ./scripts/run-modules
      # run our notebooks
      # TODO: replace with the following after fix
      - run: ./bin/run-notebooks
      #- run: PYTHONPATH=../src jupyter-nbconvert --execute notebooks/example.ipynb --to html
      #- run: PYTHONPATH=../src jupyter-nbconvert --execute notebooks/test_exchangeability.ipynb --to html
      # validate the pyproject.toml
      - run: validate-pyproject pyproject.toml
      # TODO: run: pytest once tests are added
      - name: Code coverage quick report
        run: |
          export PYTHONPATH=src
          coverage erase
          coverage run -a src/oncp/CRR.py
          coverage run -a src/oncp/classifiers.py
          coverage run -a src/oncp/CPS.py
          coverage run -a src/oncp/kernels.py
          coverage run -a src/oncp/martingale.py
          coverage report
