name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 # 2023-2024
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest nbconvert ipykernel scikit-learn scipy matplotlib validate-pyproject trove-classifiers
      - name: Parse CRR library and runs doctests
        run: python CRR.py
      - name: Parse the martingale library and run doctests
        run: python martingale.py
      # TODO: uncomment once tests are added
      # - name: Run tests
      #   run: pytest
      - name: Run notebook
        run: jupyter-nbconvert --execute example.ipynb --to html
      - name: Validate pyproject.toml
        run: validate-pyproject pyproject.toml
