name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 # 2023-2024
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest nbconvert ipykernel scikit-learn scipy matplotlib validate-pyproject trove-classifiers
      # parse libraries and run doctests:
      - run: python classifiers.py
      - run: python CPS.py
      - run: python CRR.py
      - run: python kernels.py
      - run: python martingale.py
      # run our notebooks
      - run: jupyter-nbconvert --execute example.ipynb --to html
      - run: jupyter-nbconvert --execute test_exchangeability.ipynb --to html
      # validate the pyproject.toml
      - run: validate-pyproject pyproject.toml
      # TODO: run: pytest once tests are added
